commands:
- subscribe: anton/second_light
  script: "scripts/outlet C %state% a 1 2"
- subscribe: anton/main_light
  script: "scripts/switch 1 %state%"
- subscribe: hanna/second_light
  script: "scripts/outlet C %state% a 1 3"
