info:
    host: "host"
    port: 443
    username: "username"
    password: "password"
    ssl: True
commands:
  - subscribe: anton/second_light
    python: "utils:ONOFF-binary"
    script: "~/.alfonslistener/scripts/Nexa-433MHz/sender 12345678 0 1 2 %payload%"
  - subscribe: anton/main_light
    python: "utils:ONOFF-binary"
    script: "~/.alfonslistener/scripts/Nexa-433MHz/sender 12345678 0 1 1 %payload%"
